### ISSUE TITLE
Issue when 'Rate trade'

### ISSUE THREAD

**Issue by ianleggett** [ianleggett/TinanceUI#58]
I see a stack trace in JS console after doing rate trade. 

index.js:1 Warning: Failed prop type: Material-UI: The prop `name` is required (when `readOnly` is false).
Additionally, the input name should be unique within the parent form.
    at Rating (http://localhost:3000/static/js/vendors~main.chunk.js:64368:23)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:66794:31)
    at div
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:36395:35)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:66794:31)
    at div
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:36395:35)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:66794:31)

**Comment by ianleggett** [comment]
Fixed
